print("Welcome to the tip calculator!")
total = float(input("What was the total bill?"))
print(total)
y = float(input("How much tip would you like to give?"))
print(y)
people = int(input("How many people to split the bill?"))
print(people)
total_amount = float(total) + float(total * (y / 100))
z = float(total_amount)
bill = z / people
print(f'''Each person should pay:{round(bill,2)}''')